<h3>Admin</h3>
<h4>Home</h4>
<p class="lead">Welcome to the Admin Console.</p>
<div class="row-fluid">
<div class="span6">
<h5>Search</h5>
<form action="<?php echo $this->url(array('action'=>'search','controller'=>'invoices')); ?>">
<div class="input-append">
    <input type="text" name="search" placeholder="Invoice #"><button class="btn" type="submit">Search by Invoice Number</button>
</div>
</form>
<form action="<?php echo $this->url(array('action'=>'search','controller'=>'sellers')); ?>">
<div class="input-append">
    <input type="text" name="search" placeholder="Seller Name"><button class="btn" type="submit">Search by Seller Name</button>
</div>
</form>
</div>
<div class="span6">
<h5>Approval Required (<?php echo count($this->pending); ?>)</h5>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th class="span4">Seller</th>
      <th class="span4">Created</th>
      <th class="span3">Units</th>
      <th class="span1"></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->pending as $invoice) {
/* @var $invoice Application_Model_Invoice */
?>
    <tr>
      <td><?php echo $this->sellers[$invoice->getSellerId()]->getName(); ?></td>
      <td><?php echo $invoice->getCreatedDate()->toString(Zend_Date::DATES); ?></td>
      <td><?php echo $invoice->getTotalItems(); ?></td>
      <td><a href="<?php echo $this->url(array('action'=>'view','controller'=>'invoices','id'=>$invoice->getId())); ?>" class="btn">View</a></td>
    </tr>
<?php } ?>
  </tbody>
</table>
<h5>In Transit (<?php echo count($this->approved); ?>)</h5>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th class="span4">Seller</th>
      <th class="span4">Approved</th>
      <th class="span3">Units</th>
      <th class="span1"></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->approved as $invoice) {
/* @var $invoice Application_Model_Invoice */
?>
    <tr>
      <td><?php echo $this->sellers[$invoice->getSellerId()]->getName(); ?></td>
      <td><?php echo $invoice->getApprovedDate()->toString(Zend_Date::DATES); ?></td>
      <td><?php echo $invoice->getTotalItems(); ?></td>
      <td><a href="<?php echo $this->url(array('action'=>'view','controller'=>'invoices','id'=>$invoice->getId())); ?>" class="btn">View</a></td>
    </tr>
<?php } ?>
  </tbody>
</table>
<h5>Received (<?php echo count($this->received); ?>)</h5>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th class="span4">Seller</th>
      <th class="span4">Received</th>
      <th class="span3">Units</th>
      <th class="span1"></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->received as $invoice) {
/* @var $invoice Application_Model_Invoice */
?>
    <tr>
      <td><?php echo $this->sellers[$invoice->getSellerId()]->getName(); ?></td>
      <td><?php echo $invoice->getReceivedDate()->toString(Zend_Date::DATES); ?></td>
      <td><?php echo $invoice->getTotalItems(); ?></td>
      <td><a href="<?php echo $this->url(array('action'=>'view','controller'=>'invoices','id'=>$invoice->getId())); ?>" class="btn">View</a></td>
    </tr>
<?php } ?>
  </tbody>
</table>
<h5>Processed (<?php echo count($this->processed); ?>)</h5>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th class="span4">Seller</th>
      <th class="span4">Processed</th>
      <th class="span3">Units</th>
      <th class="span1"></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->processed as $invoice) {
/* @var $invoice Application_Model_Invoice */
?>
    <tr>
      <td><?php echo $this->sellers[$invoice->getSellerId()]->getName(); ?></td>
      <td><?php echo $invoice->getProcessedDate()->toString(Zend_Date::DATES); ?></td>
      <td><?php echo $invoice->getTotalItems(); ?></td>
      <td><a href="<?php echo $this->url(array('action'=>'view','controller'=>'invoices','id'=>$invoice->getId())); ?>" class="btn">View</a></td>
    </tr>
<?php } ?>
  </tbody>
</table>
</div>
</div>
