<h3>Upload Sell List</h3>
<h4>Step 3 - Generate Purchase Order</h4>
<div class="alert alert-info">
    <strong>Please wait:</strong> We are currently processing your sell list against our records. Your browser will automatically redirect you to the next page when this process is completed.
</div>
<div style="height:100px; padding:100px 0;">
<div style="width:100px; height:100px; margin-left:auto; margin-right:auto;"><img height="100" width="100" src="<?php echo $this->baseUrl('/img/ajax-loader.gif'); ?>"/></div>
</div>
