Dear <?php echo $this->contactName; ?>,

Your invoice #<?php echo $this->sellerInvoiceNumber; ?> has been marked as Approved for Shipment.

You can view shipping instructions on the site (https://www.sellbooksdirect.com/). Just click on the "Invoices" section under "My Account".

Regards,

Sell Books Direct

For general questions about the program: usedtextbooks-bulk@amazon.com
For issues related to the site and processing: support@sellbooksdirect.com
