Dear <?php echo $this->contactName; ?>,

An account has been created for you on Sell Books Direct (https://www.sellbooksdirect.com/).

Your account details are:

Username: <?php echo $this->contactEmail; ?>

Temporary Password: <?php echo $this->temp; ?>

When you login to the site for the first time, you will have an opportunity to complete your registration and create a permanent password.

Regards,

Sell Books Direct

For general questions about the program: usedtextbooks-bulk@amazon.com
For issues related to the site and processing: support@sellbooksdirect.com