Dear <?php echo $this->contactName; ?>,

We have received a password reset request for your login "<?php echo $this->contactEmail; ?>".

If you did not request this password reset, someone else may be trying to access your account without your consent.

Your temporary password is: <?php echo $this->temp; ?>

To continue the password reset process, login to the site using this temporary password (https://www.sellbooksdirect.com/).

Regards,

Sell Books Direct

For general questions about the program: usedtextbooks-bulk@amazon.com
For issues related to the site and processing: support@sellbooksdirect.com