<div class="row-fluid">
    <div class="span6">
        <form method="post">
            <fieldset>
            <legend>Login</legend>
            <p>NOTE: This account is distinct from any other Amazon accounts you may have.</p>
            <?php echo $this->form->username; ?>
            <?php echo $this->form->password; ?>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Login</button><br /><br /><br />
                <button name="forgot" value="forgot" class="btn">Forgot password?</button>
                <p style="padding-top: 15px;">If clicking "Forgot password?", please first enter your email address.</p>
            </div>
            </fieldset>
        </form>
    </div>
    <div class="span6 well-large">
        <h3>How It Works</h3>
        <h4><span class="badge badge-success">1</span> Upload Inventory</h4>Upload a simple Excel/CSV spreadsheet of your textbook inventory.
        <h4><span class="badge badge-success">2</span> Amazon PO Is Generated</h4>Our system automatically matches up your inventory with Amazon's bulk buy list and outputs a purchase order within seconds.
        <h4><span class="badge badge-success">3</span> Ship For FREE</h4>Shipping is always FREE via McKenzie's freight collect account.
        <h4><span class="badge badge-success">4</span> Get Paid</h4>Payment via check or ACH in NET 30 terms (from receipt of books).
        <hr>
        <p>Access to this website must be approved by McKenzie Books and Amazon.com.</p>
        <p>For approval, or for questions related to the site and processing, email us at: <a href="mailto:support@sellbooksdirect.com">support@sellbooksdirect.com</a> or call 503-488-5349.</p>
    </div>
</div>


