<h2>Seller Account Registration</h2>
<p class="lead">Complete the form below to create a seller account, to enable you to upload sell lists to us.</p>
<form method="post">
    <legend>Seller Details</legend>
    <p><small>All fields are required unless marked optional.</small></p>
    <?php echo $this->form; ?>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Complete Registration</button>
    </div>
</form>
