<form method="post">
    <legend>User Details</legend>
    <p><small>All fields are required unless marked optional.</small></p>
    <?php echo $this->form; ?>
    <label>Change Password</label>
    <input class="input-xlarge" type="password" name="changePassword"><span class="help-inline">(enter a new password if you wish to change the current password)</span>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Save User</button>
    </div>
</form>
