<form method="post">
    <legend>New Seller Details</legend>
    <p>The seller will receive an email with a link back to this site, and a temporary password. They will then be required to complete the registration process and create a permanent password</p>
    <p><small>All fields are required unless marked optional.</small></p>
    <?php echo $this->form; ?>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Add New Seller</button>
    </div>
</form>
