<h3>Sellers</h3>
<h4>Viewing Seller</h4>
<div class="row-fluid">
<div class="span12">
<dl class="dl-horizontal">
  <dt>Company</dt>
  <dd><?php echo $this->seller->getName(); ?></dd>
  <dt>Status</dt>
  <dd><?php echo Application_Model_Seller::$sellerStatusTypes[$this->seller->getSellerStatus()]; ?></dd>
  <dt>Contact Name</dt>
  <dd><?php echo $this->seller->getContactName(); ?></dd>
  <dt>Contact Email</dt>
  <dd><?php echo $this->seller->getContactEmail(); ?></dd>
  <dt>Contact Phone</dt>
  <dd><?php echo $this->seller->getContactPhone(); ?></dd>
  <dt>Payee Name</dt>
  <dd><?php $payeeName = $this->seller->getPayeeName(); echo (empty($payeeName)?'<i>None provided</i>':$payeeName); ?></dd>
  <dt>Address 1</dt>
  <dd><?php echo $this->seller->getPaymentAddress1(); ?></dd>
  <dt>Address 2</dt>
  <dd><?php $paymentAddress2 = $this->seller->getPaymentAddress2(); echo (empty($payeeName)?'<i>None provided</i>':$paymentAddress2); ?></dd>
  <dt>Payment City</dt>
  <dd><?php echo $this->seller->getPaymentCity(); ?></dd>
  <dt>Payment State</dt>
  <dd><?php echo $this->seller->getPaymentState(); ?></dd>
  <dt>Payment Zip</dt>
  <dd><?php echo $this->seller->getPaymentZip(); ?></dd>
  <dt>Email Notify</dt>
  <dd><?php echo ($this->seller->getEmailNotify()?'Yes':'No'); ?></dd>
</dl>
</div>
</div>
<h5>Seller Invoices</h5>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th class="span2">Invoice #</th>
      <th class="span3">Created</th>
      <th class="span2">Status</th>
      <th class="span2">Quantity</th>
      <th class="span2">Total</th>
      <th class="span1"></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->invoices as $invoice) {
/* @var $invoice Application_Model_Invoice */
?>
    <tr>
      <td><?php echo $invoice->getSellerInvoiceNumber(); ?></td>
      <td><?php echo $invoice->getCreatedDate()->toString(); ?></td>
      <td><?php echo $invoice::$shortStatusTypes[$invoice->getInvoiceStatus()]; ?></td>
      <td><?php echo $invoice->getTotalItems(); ?></td>
      <td>$ <?php echo number_format($invoice->getTotalPrice(), 2); ?></td>
      <td><a href="<?php echo $this->url(array('controller'=>'invoices','action'=>'view','id'=>$invoice->getId())); ?>" class="btn">View</a></td>
    </tr>
<?php } ?>
  </tbody>
</table>
