<h3>Invoices</h3>
<h4>List All</h4>
<p class="lead">On this page you can view recent invoices in the system (past 90 days). Or, search for any invoice.</p>
<form action="search">
<div class="input-append">
    <input type="text" name="search" placeholder="Invoice #"><button class="btn" type="submit">Search by Invoice Number</button>
</div>
</form>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Invoice #</th>
      <th>Seller</th>
      <th>Created</th>
      <th>Status</th>
      <th>Quantity</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->invoices as $invoice) {
/* @var $invoice Application_Model_Invoice */
?>
    <tr>
      <td><?php echo $invoice->getSellerInvoiceNumber(); ?></td>
      <td><?php echo $this->sellers[$invoice->getSellerId()]->getName(); ?></td>
      <td><?php echo $invoice->getCreatedDate()->toString(); ?></td>
      <td><?php echo $invoice::$shortStatusTypes[$invoice->getInvoiceStatus()]; ?></td>
      <td><?php echo $invoice->getTotalItems(); ?></td>
      <td>$ <?php echo number_format($invoice->getTotalPrice(), 2); ?></td>
      <td><a href="<?php echo $this->url(array('action'=>'view','id'=>$invoice->getId())); ?>" class="btn">View</a></td>
    </tr>
<?php } ?>
  </tbody>
</table>
