<?php
$invoice = $this->invoice;
/* @var $invoice Application_Model_Invoice */
?>
<h3>Invoices</h3>
<h4>Viewing Invoice</h4>
<div class="row-fluid">
<div class="span5">
    <?php

    // nebraska seller id = 1163
    if ($invoice->getSellerId() == 1163 && ($invoice->getInvoiceStatus() == $invoice::STATUS_PENDING_APPROVAL || $invoice->getInvoiceStatus() == $invoice::STATUS_APPROVED)) { ?>

        <p>WARNING: only update the invoice number if it has not yet been pushed in the Amazon daily report at 5pm.</p>
        <div class="input-append" >
            <form method="POST" action="/admin/invoices/update/id/<?php echo $invoice->getId(); ?>">
                <label><strong>Invoice #</strong></label>
                <input style="width: 150px;" type="text" name="invoice-number" value="<?php echo $invoice->getSellerInvoiceNumber(); ?>" />
                <button class="btn btn-inverse" type="submit">Update</button>
            </form>
        </div>
<dl class="dl-horizontal">
        <?php } else { ?>
<dl class="dl-horizontal">
  <dt>Invoice #</dt>
        <dd><?php echo $invoice->getSellerInvoiceNumber(); ?></dd>
        <?php } ?>
  <dt>Ship date</dt>
  <dd><?php echo $invoice->getShipDate()->toString(Zend_Date::DATES); ?></dd>
  <dt>Created on</dt>
  <dd><?php echo $invoice->getCreatedDate(); ?></dd>
  <dt>Approved on</dt>
  <dd><?php echo (($invoice->getApprovedDate())?$invoice->getApprovedDate():'-'); ?></dd>
  <dt>Received on</dt>
  <dd><?php echo (($invoice->getReceivedDate())?$invoice->getReceivedDate():'-'); ?></dd>
  <dt>Processed on</dt>
  <dd><?php echo (($invoice->getProcessedDate())?$invoice->getProcessedDate():'-'); ?></dd>
  <dt>Paid on</dt>
  <dd><?php echo (($invoice->getPaidDate())?$invoice->getPaidDate():'-'); ?></dd>
  <?php if ($invoice->getInvoiceStatus() == $invoice::STATUS_CANCELLED) { ?>
  <dt>Cancelled on</dt>
  <dd><?php echo (($invoice->getCancelledDate())?$invoice->getCancelledDate():'-'); ?></dd>
  <?php } ?>
</dl>
</div>
<div class="span7">
<form method="post">
    <div class="row-fluid">
        <div class="span6">
        <?php echo $this->formSelect('invoiceStatus', $invoice->getInvoiceStatus(), array('class'=>'span12'), $invoice::$_invoiceStatusTypes); ?>
        </div>
        <div class="span6">
        <button type="submit" class="btn btn-primary span12" name="submit" value="status">Change Invoice Status</button>
        </div>
    </div>
</form>
<div class="btn-group">
    <a href="<?php echo $this->url(array('action'=>'download')); ?>" class="btn">Download as .csv</a>
</div>
</div>
</div>
<div class="row-fluid">
<table class="table table-striped table-condensed">
<thead>
    <tr>
        <th class="span6">ISBN10/ISBN13</th>
        <th style="text-align:right;" class="span2">Quantity</th>
        <th style="text-align:right;" class="span2">Item Price</th>
        <th style="text-align:right;" class="span2">Line Total</th>
    </tr>
</thead>
<tbody>
<?php foreach ($invoice->getLineItems() as $item) {
/* @var $item Application_Model_InvoiceItem */ ?>
    <tr>
        <td><?php echo $item->getIsbn13(); ?></td>
        <td style="text-align:right;"><?php echo $item->getQuantity(); ?></td>
        <td style="text-align:right;">$ <?php echo number_format($item->getPrice(),2); ?></td>
        <td style="text-align:right;">$ <?php echo number_format($item->getTotal(),2); ?></td>
    </tr>
<?php } ?>
    <tr>
        <td><strong>Totals</strong></td>
        <td style="text-align:right;"><strong><?php echo $invoice->getTotalItems(); ?></strong></td>
        <td></td>
        <td style="text-align:right;"><strong>$ <?php echo number_format($invoice->getTotalPrice(),2); ?></strong></td>
    </tr>
</tbody>
</table>
</div>
<h5>Notes</h5>
<div class="row-fluid">
<table class="table table-striped table-condensed">
<thead>
    <tr>
        <th class="span8">Note</th>
        <th class="span2">Author</th>
        <th class="span2">Date Created</th>
    </tr>
</thead>
<tbody>
<?php
$notes = array_reverse($invoice->getNotes());
foreach ($notes as $note) {
/* @var $note Application_Model_InvoiceNote */ ?>
    <tr>
        <td><?php echo $note->getNote(); ?></td>
        <td><?php echo $note->getWho(); ?></td>
        <td><?php echo $note->getDate()->toString(); ?></td>
    </tr>
<?php } ?>
</tbody>
</table>
</div>
<div class="row-fluid">
<form method="post">
<legend>Add new note</legend>
<textarea name="note" rows="5" class="span10"></textarea>
<button class="span2 pull-right" type="submit" name="submit" value="note">Add Note</button>
</form>
</div>
<h5>Changelog</h5>
<div class="row-fluid">
<table class="table table-striped table-condensed">
<thead>
    <tr>
        <th class="span5">Action</th>
        <th class="span5">User</th>
        <th class="span2">Action Date</th>
    </tr>
</thead>
<tbody>
<?php
$actions = array_reverse($invoice->getActions());
foreach ($actions as $action) {
    /* @var $action Application_Model_InvoiceAction */ ?>
    <tr>
        <td><?php echo $action::$actions[$action->getWhat()]; ?></td>
        <td><?php echo $action->getWho(); ?></td>
        <td><?php echo $action->getActionDate()->toString(); ?></td>
    </tr>
<?php } ?>
</tbody>
</table>
</div>
